### ISSUE TITLE
Strange behaviour on delete

### ISSUE THREAD

**Issue by Alex293** [hfrahmann/HFCardCollectionViewLayout#3]
If i delete a card while it's flipped the card will disappear and another card will be considered as flipped and will be flipped back. Everything works as expected but we can see a flip animation on the top stacked card which feels weird.

**Comment by hfrahmann** [comment]
New code to delete a card. The completion block of _ flipRevealedCardBack_ is also called when the card is not flipped.
```
var index = 0
if(self.cardCollectionViewLayout!.revealedIndex >= 0) {
    index = self.cardCollectionViewLayout!.revealedIndex
}
self.cardCollectionViewLayout?.flipRevealedCardBack(completion: {
    self.colorArray.remove(at: index)
    self.collectionView?.deleteItems(at: [IndexPath(item: index, section: 0)])
    self.cardCollectionViewLayout?.unrevealCard(completion: {
        if(self.colorArray.count == 1) {
            self.cardCollectionViewLayout?.revealCardAt(index: 0)
        }
    })
})
```

It should now look like this:

![hfcdeletefast](https://cloud.githubusercontent.com/assets/2393255/23896075/53029e72-08a8-11e7-8e78-e84fe4f72fd3.gif)
