### ISSUE TITLE
Swipe is almost impossible in embedded table

### ISSUE THREAD

**Issue by Alex293** [hfrahmann/HFCardCollectionViewLayout#4]
Hi,

It's almost impossible to get the swipe to edit on rows on the embedded table into your layout. The gesture is almost always stolen by the scroll view of the layout. Do you have any idea how to improve this ?

The bug is easy to reproduce by adding some data to the table and an action on swipe like this : 
func tableView(_ tableView: UITableView, editActionsForRowAt indexPath: IndexPath) -> [UITableViewRowAction]?
    {
       let anAction = UITableViewRowAction(style: .default, title: "An Action")
        {
            (action, indexPath) -> Void in
            //
        }
return [anAction]

**Comment by hfrahmann** [comment]
Hi,

it should be fixed with the version 0.4.

![simulator screen shot 14 03 2017 10 30 42](https://cloud.githubusercontent.com/assets/2393255/23895811/6a547678-08a7-11e7-8d8b-dd0e1be00d66.png)

**Comment by Alex293** [comment]
Working fine ! Thanks for your reactivity ! There is still two debug print in the release code but i removed them you may want to do the same

**Comment by hfrahmann** [comment]
Thanks for the note. I already pushed a commit and they will be removed within the next version. ;-)
