### ISSUE TITLE
iOS 11 contentInset cards under Navigation Bar

### ISSUE THREAD

**Issue by JWShroyer** [hfrahmann/HFCardCollectionViewLayout#6]
Now with iOS 11 and the introduction of the safe area content insets, using the standard contentInset in the HFCardCollectionViewLayout will not work properly. Instead, the adjustedContentInset should be used to get the total adjustment including the safe area and any custom insets.

**Comment by hfrahmann** [comment]
I guess with your pull request it should be fixed.
